# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Agorakit
docs_dir: docs/
theme:
  name: material
  features:
    #- navigation.sections
    - navigation.path
    - search.suggest
    - search.highlight
    - navigation.tracking
    - navigation.tabs
plugins:
  - offline
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: fr
          name: Français
          build: true
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - callouts
watch:
  - includes





nav:
  - What is Agorakit?: index.md
  - 'Using Agorakit': 
    - Signing up: sign_up.md
    - First steps after install : first_steps.md
    - Using Agorakit : usage.md
    - Creating & managing a group : group.md
  - 'Running Agorakit':
    - Installation : install.md
    - Advanced configurations : advanced_config.md
    - Upgrading : upgrade.md
  
  - 'Contributing':
    - Setup a development server : development.md
    - Useful artisan commands : artisan.md
    - Writing documentation : documentation.md
  - 'Contact and support':
    - How to contact us : contact.md
