# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Agorakit
docs_dir: docs/
theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.sections

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
    
repo_url: https://github.com/agorakit/documentation
plugins:
  - privacy
  - offline
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: fr
          name: Français
          build: true
markdown_extensions:
  - mdx_linkify
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - callouts
  - toc:
        title: On this page
watch:
  - includes


nav:
  - Introduction: index.md
  - Technical Setup:
    - Installation: install.md
    - Configuration: config.md
    - Upgrading: upgrade.md
  - Using Agorakit:
    - Signing up: sign_up.md
    - Managing groups: group.md
    - Basic usage: usage.md
    - Using tags: tags.md
    - Users: users.md
    - Deleting content: delete_content.md
  - Contributing:
    - How to contribute: contribute.md
    - Documentation: documentation.md
    - Localization: localization.md
  - Development:
    - Development overview: development.md
    - Localhost setup: localhost.md
    - Testing: testing.md
    - Useful commands: artisan.md
  - Contact Us: contact.md
