site_name: Agorakit docs
nav:
    - Home: index.md
    - 'Admin guide':
        - Install: install.md
        - Update: update.md
        - Configure inbound email: inbound_email.md
        - Configure external authentification: external_authentification.md
        - For developers: development.md
    - 'User guide': usage.md
repo_url: https://github.com/agorakit/documentation/
markdown_extensions:
    - toc:
        permalink: "#"
theme:
  name: 'material'
